postgres: &postgres
  adapter: postgresql
  host: localhost
  port: 5432

development:
  <<: *postgres
  database: notifiable-gcm-spacialdb-development

test:
  <<: *postgres
  database: notifiable-gcm-spacialdb-test